# Use an official Node.js runtime as a base image
FROM node:21.5.0-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire application to the working directory
COPY . .

# Build the React application
RUN npm run build
RUN npm install -g serve

# Run tests (replace with your actual test command)
# RUN npm test

# Expose the port that the application will run on (adjust if needed)
EXPOSE 3030

# Specify the command to run your application
CMD ["serve", "-s", "dist", "-l", "3030"]